import { createHash } from "node:crypto";
import {
  lstat,
  mkdir,
  mkdtemp,
  readFile,
  realpath,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { isAbsolute, join, relative, resolve } from "node:path";

import { compareCodeUnits, stableStringify } from "@anvilmark/project-contract";
import { z } from "zod/v4";

import type { Clock } from "../clock.js";
import { systemClock } from "../clock.js";
import type { AdapterIdentity, AdapterOutcome } from "../envelope.js";
import {
  adapterError,
  available,
  isAvailable,
  notAvailable,
} from "../envelope.js";
import { ADAPTER_PROTOCOL_VERSION } from "../version.js";
import type { AdapterProbe, EvidenceAdapter } from "../evidence/adapter.js";
import type {
  EvaluationPlan,
  EvaluationProjection,
  ProviderReach,
  ProviderRegistration,
  ProviderRegistry,
  RemoteAuthorization,
  SpecRejection,
} from "./promptfoo-spec.js";
import {
  buildProviderRegistry,
  describeOutboundProjection,
  expectedCaseCount,
  isRejection,
  planEvaluation,
} from "./promptfoo-spec.js";
import {
  PROBE_TIMEOUT_BOUNDS,
  VERIFIED_PROMPTFOO_VERSIONS,
  createRuntimeLayout,
  digestFile,
  effectiveResourceLimits,
  isBoundedInteger,
  isVerifiedPromptfooVersion,
  resolveExecutable,
  resourceLimitCeilings,
  runtimeLayout,
} from "./promptfoo-execution.js";
import type { ResourceLimits } from "./promptfoo-execution.js";
import { artifactPromptfooVersion, bindResultRows } from "./promptfoo-rows.js";
import type { BuiltEvidence } from "../evidence/builder.js";
import { buildEvidenceRecord } from "../evidence/builder.js";
import { runSubprocess } from "../subprocess/runner.js";

/** The candidate-side expectation, as the contract defines it. */
export interface ExpectedEvaluation {
  readonly provider_id: string;
  readonly configuration_hash: string;
}

/**
 * Everything that, if changed, makes a previous result inapplicable.
 *
 * A result is only evidence about the exact experiment that produced it.
 * Change the dataset, the prompt, the candidate, the model configuration, or
 * the evaluator, and the old numbers describe something else. Each identity is
 * carried into the contract individually so that a later reader can see WHICH
 * input moved, not merely that something did.
 */
/**
 * `sha256:` followed by 64 lower-case hex characters.
 *
 * An opaque caller-supplied string is not proof of what ran. Requiring the
 * algorithm and a fixed representation means a fabricated value is rejected
 * rather than recorded as though it were a measurement's identity.
 */
export const DIGEST_PATTERN = /^sha256:[0-9a-f]{64}$/;

export function digestOf(content: string): string {
  return `sha256:${createHash("sha256").update(content, "utf8").digest("hex")}`;
}

/**
 * What each digest covers.
 *
 * Stated explicitly because "a digest" means nothing without the bytes it was
 * taken over. Every one of these is DERIVED by the adapter from the inputs it
 * can actually read, and then compared with the caller's expectation. A
 * caller-supplied value is never recorded as though it were verified.
 *
 * | digest                     | canonical bytes                                        |
 * | -------------------------- | ------------------------------------------------------ |
 * | `config_digest`            | the exact generated bytes passed to `-c`               |
 * | `dataset_hash`             | dataset id, version, and each row WITHOUT its `assert` |
 * | `prompt_hash`              | the ordered list of inline prompt contents             |
 * | `evaluator_hash`           | default assertions plus each row's `assert`, in order  |
 * | `model_configuration_hash` | provider id, config data, and credential NAMES         |
 *
 * These cover DATA the spec holds, not files on disk. An evaluation whose
 * inputs are not fully present cannot have a verifiable identity, so it is
 * refused before it runs rather than recorded with a digest that proves
 * nothing.
 */
export interface EvaluationIdentity {
  readonly workload_ref: string;
  readonly candidate_ref: string;
  readonly dataset_ref: string;
  readonly dataset_version: string;
  /** Expected digests. Each is compared with the value the adapter derives. */
  readonly dataset_hash: string;
  readonly prompt_hash: string;
  readonly evaluator_hash: string;
  readonly model_configuration_hash: string;
  /**
   * The provider this candidate is expected to run against. Checked against
   * what the tool reports; a difference is an attribution failure.
   */
  readonly provider_id?: string | null;
}

/** The identity as recorded, including the values the adapter established. */
export interface VerifiedEvaluationIdentity extends EvaluationIdentity {
  readonly config_digest: string;
  readonly provider_id: string;
  /**
   * Where the evaluation ran, from trusted provider policy. Part of the hashed
   * identity, so evidence measured against one endpoint is never current for
   * another: the same spec run locally, or against a different host, is a
   * different measurement.
   */
  readonly provider_reach: ProviderReach;
  readonly destination_identity: string;
}

export function evaluationIdentityHash(
  identity: EvaluationIdentity | VerifiedEvaluationIdentity,
): string {
  return createHash("sha256")
    .update(stableStringify(identity), "utf8")
    .digest("hex");
}

/**
 * The documented promptfoo output-file envelope.
 *
 * Written by `promptfoo eval -o <file>.json`, as `OutputFile` in
 * `src/types/index.ts`: `evalId`, `results`, `config`, `shareableUrl`. In both
 * `EvaluateSummaryV2` and `EvaluateSummaryV3` the `version` and `timestamp`
 * live INSIDE `results`, so that is where this parser reads them; the
 * top-level positions are tolerated but no current version emits them.
 *
 * `results.stats` — `successes`, `failures`, `errors`, `tokenUsage` — is the
 * part CI is documented to read and the part this adapter depends on.
 *
 * Source, pinned at commit 0170037970dd4732f7542c60ceafa5f4951289de:
 *   src/types/index.ts, src/util/output.ts
 */
const TokenUsageSchema = z
  .object({
    total: z.number().nonnegative().optional(),
    prompt: z.number().nonnegative().optional(),
    completion: z.number().nonnegative().optional(),
    cached: z.number().nonnegative().optional(),
    numRequests: z.number().nonnegative().optional(),
  })
  .loose();

const StatsSchema = z
  .object({
    successes: z.number().int().nonnegative(),
    failures: z.number().int().nonnegative(),
    errors: z.number().int().nonnegative().optional(),
    tokenUsage: TokenUsageSchema.optional(),
    namedScores: z.record(z.string(), z.number()).optional(),
  })
  .loose();

/**
 * Per-prompt aggregate metrics. This is where promptfoo reports `namedScores`,
 * total latency, and cost — not on `stats`, which carries the counts CI reads.
 */
const PromptSchema = z
  .object({
    label: z.string().optional(),
    metrics: z
      .object({
        score: z.number().optional(),
        totalLatencyMs: z.number().nonnegative().optional(),
        cost: z.number().nonnegative().optional(),
        namedScores: z.record(z.string(), z.number()).optional(),
        tokenUsage: TokenUsageSchema.optional(),
      })
      .loose()
      .optional(),
  })
  .loose();

/** A row in `results.results[]`; its provider is an object with an id. */
const ResultRowSchema = z
  .object({
    provider: z
      .union([z.string().min(1), z.object({ id: z.string().min(1) }).loose()])
      .optional(),
    /**
     * Read as unknown and checked by `classifyCaseRow`, so a missing or
     * mistyped outcome is reported as a contradiction in THIS row rather than
     * as a generic envelope failure.
     */
    success: z.unknown().optional(),
    failureReason: z.unknown().optional(),
  })
  .loose();

/**
 * `ResultFailureReason`, as defined at the pinned promptfoo commit.
 *
 * Source: promptfoo 0.122.0, commit 0170037970dd4732f7542c60ceafa5f4951289de,
 * `src/types/index.ts` lines 375-382:
 *   NONE: 0   -- "The test passed, or we don't know exactly why the test case
 *               failed."
 *   ASSERT: 1 -- "The test case failed because an assertion rejected it."
 *   ERROR: 2  -- "Test case failed due to some other error."
 */
export const PROMPTFOO_FAILURE_REASON = {
  NONE: 0,
  ASSERT: 1,
  ERROR: 2,
} as const;

/**
 * Classify one per-case row the way promptfoo counted it into `stats`.
 *
 * Source, same pinned commit, `src/evaluator.ts`:
 *
 * - `trackRowStats` (line 3387) is the rule the summary was built with:
 *   `success` true is a success; otherwise `failureReason === ERROR` is an
 *   error; otherwise -- ASSERT or NONE -- a failure.
 * - Rows start as `success: false, failureReason: NONE` (lines 1224-1225).
 *   `applyGradingResult` (line 583) sets `success` from the grading pass, and
 *   only on a failed pass sets `failureReason = ASSERT`. Every merge of a later
 *   grading result is `previous && next` (lines 2079, 2089, 2105), so nothing
 *   turns a failed row into a passing one. The only paths that set `success`
 *   true leave `failureReason` at NONE, so a passing row naming ASSERT or ERROR
 *   is not something promptfoo produces: it is refused as contradictory.
 * - `applyGradingError` (line 606), a provider `response.error` (lines
 *   1301-1305), and both timeout results set `success: false,
 *   failureReason: ERROR`.
 *
 * The `error` STRING is deliberately not read. It does not distinguish the
 * categories: `applyGradingResult` sets it on an ordinary assertion failure
 * (line 585), and `applyEmptyResponseOutcome` (line 1334) sets
 * `error = "No output"` (line 1340) while leaving `failureReason` at NONE, which
 * `trackRowStats` counts as a FAILURE. Treating "has an error message" as
 * "is an error" would miscount both.
 *
 * Confirmed against real 0.122.0 output: a passing assertion produced
 * `(true, 0)`, a failing one `(false, 1)` with an error message, an invalid
 * regular expression `(false, 1)` -- an assertion failure, not an error -- and
 * an unreachable local HTTP endpoint `(false, 2)`.
 */
export function classifyCaseRow(row: {
  readonly success?: unknown;
  readonly failureReason?: unknown;
}):
  | { readonly counted: "successes" | "failures" | "errors" }
  | { readonly problem: string } {
  if (typeof row.success !== "boolean") {
    return {
      problem:
        "has no boolean `success`, so whether this case passed cannot be established",
    };
  }
  const reason = row.failureReason;
  if (
    reason !== PROMPTFOO_FAILURE_REASON.NONE &&
    reason !== PROMPTFOO_FAILURE_REASON.ASSERT &&
    reason !== PROMPTFOO_FAILURE_REASON.ERROR
  ) {
    return {
      problem:
        "has no recognised `failureReason` (0, 1 or 2), so how this case was counted cannot be established",
    };
  }
  if (row.success) {
    if (reason !== PROMPTFOO_FAILURE_REASON.NONE) {
      return {
        problem:
          "reports success while naming a failure reason, which promptfoo does not produce; the row contradicts itself",
      };
    }
    return { counted: "successes" };
  }
  return {
    counted: reason === PROMPTFOO_FAILURE_REASON.ERROR ? "errors" : "failures",
  };
}

/** An entry in the documented `results.providers[]` collection. */
const ProviderEntrySchema = z.union([
  z.string().min(1),
  z.object({ id: z.string().min(1) }).loose(),
]);

const PromptfooOutputSchema = z
  .object({
    evalId: z.string().min(1).optional(),
    version: z.number().optional(),
    timestamp: z.string().min(1).optional(),
    results: z
      .object({
        version: z.number().optional(),
        timestamp: z.string().min(1).optional(),
        stats: StatsSchema,
        results: z.array(ResultRowSchema).optional(),
        prompts: z.array(PromptSchema).optional(),
        providers: z.array(ProviderEntrySchema).optional(),
      })
      .loose(),
  })
  .loose();

function providerIdOf(value: unknown): string | null {
  if (typeof value === "string") {
    return value.length > 0 ? value : null;
  }
  if (value !== null && typeof value === "object" && "id" in value) {
    const id = (value as { id?: unknown }).id;
    return typeof id === "string" && id.length > 0 ? id : null;
  }
  return null;
}

/**
 * Every provider the artifact names, from every documented location.
 *
 * Reading only `results.prompts[].provider` was the defect: an artifact that
 * lists its providers under `results.providers[]` sailed through with no
 * provider established at all, and the evidence recorded `provider_id: null`.
 */
export function collectProviders(
  output: z.infer<typeof PromptfooOutputSchema>,
): {
  readonly providers: readonly string[];
  readonly sources: readonly string[];
} {
  const found = new Map<string, Set<string>>();
  const note = (id: string | null, source: string): void => {
    if (id === null) {
      return;
    }
    const sources = found.get(id) ?? new Set<string>();
    sources.add(source);
    found.set(id, sources);
  };

  for (const prompt of output.results.prompts ?? []) {
    note(
      providerIdOf((prompt as { provider?: unknown }).provider),
      "results.prompts[].provider",
    );
  }
  for (const row of output.results.results ?? []) {
    note(providerIdOf(row.provider), "results.results[].provider");
  }
  for (const entry of output.results.providers ?? []) {
    note(providerIdOf(entry), "results.providers[]");
  }

  const providers = [...found.keys()].sort(compareCodeUnits);
  const sources = [
    ...new Set([...found.values()].flatMap((set) => [...set])),
  ].sort(compareCodeUnits);
  return { providers, sources };
}

export interface PromptfooRequest {
  readonly evidenceId: string;
  /**
   * The evaluation, as data ANVILMARK owns. The promptfoo config is GENERATED
   * from this and is the only thing the tool ever reads.
   *
   * This is the SINGLE authority. Workload, candidate, dataset, dataset
   * version, provider and credential names are all read from here. There is
   * deliberately no second declaration to disagree with it: the previous
   * request carried its own `identity` and `credentialEnvNames`, only some
   * fields of which were compared, and an evaluation of `candidate.real` was
   * recorded as evidence about `candidate.other` because the uncompared fields
   * were copied onto the record verbatim.
   */
  readonly spec: unknown;
  /**
   * Accepted only so a caller pointing at an existing promptfoo config gets a
   * clear refusal rather than a type error. It is never interpreted: parsing
   * an arbitrary config cannot be made sound, so it always returns
   * `unsupported_configuration`.
   */
  readonly configPath?: string;
  /** ANVILMARK-controlled directory. The result artifact is written here. */
  readonly dataDirectory: string;
  /**
   * Name for the result artifact. A plain file name only: no separators, no
   * traversal, no absolute path. The adapter places it inside a unique
   * per-run directory it creates and removes.
   */
  readonly outputFileName?: string;
  readonly timeoutMs?: number;
  readonly maxOutputBytes?: number;
  /**
   * Largest artifact the adapter will read. The subprocess stdout cap does
   * not bound a file the tool writes.
   */
  readonly maxArtifactBytes?: number;
  /**
   * A human authorization for the exact outbound projection, required before a
   * REMOTE provider runs. Milestone 2 does not create these and cannot: it has
   * no interactive surface. Milestone 3's flow shows the projection and records
   * the decision; this adapter only checks that a matching record exists.
   */
  readonly authorization?: RemoteAuthorization;
  readonly constraintRefs: readonly string[];
  readonly metricUnits?: Readonly<Record<string, string>>;
}

/**
 * Every field a request may carry. Anything else is refused.
 *
 * The request is a closed shape because the caller that supplies an evaluation
 * is not trusted to choose how it is measured. A previous version accepted
 * `executable`, `readEnv` and `baseEnv` here: a fake binary could emit a
 * fabricated artifact that became T3 evidence, credential values could be
 * injected, and a bare executable name could resolve to one program for the
 * version probe and another for the run. Those are now construction-time
 * options, and an old or hostile request naming them is told so rather than
 * quietly ignored.
 */
export const PROMPTFOO_REQUEST_FIELDS: readonly string[] = [
  "evidenceId",
  "spec",
  "configPath",
  "dataDirectory",
  "outputFileName",
  "timeoutMs",
  "maxOutputBytes",
  "maxArtifactBytes",
  "authorization",
  "constraintRefs",
  "metricUnits",
];

export const PROMPTFOO_IDENTITY: AdapterIdentity = {
  id: "promptfoo",
  kind: "evaluation",
  version: null,
  execution: "local",
  protocol_version: ADAPTER_PROTOCOL_VERSION,
};

/**
 * Environment that isolates the tool from shared state and from the network
 * features ANVILMARK does not want it using.
 *
 * Sharing and telemetry are off by default because an evaluation carries the
 * user's prompts and dataset rows, and those are default-denied to everything
 * outside the machine.
 */
/** A plain file name: no separators, no traversal, no absolute path. */
export function isSafeArtifactName(name: string): boolean {
  if (name.length === 0 || name === "." || name === "..") {
    return false;
  }
  if (isAbsolute(name)) {
    return false;
  }
  return !/[\\/]/.test(name) && !name.includes("\0");
}

/**
 * Is `candidate` genuinely inside `root` once symlinks are resolved?
 *
 * A directory that resolves outside the declared data directory would put the
 * artifact — and the recursive cleanup that follows — somewhere the caller did
 * not authorise.
 */
export async function isContainedIn(
  root: string,
  candidate: string,
): Promise<boolean> {
  const [realRoot, realCandidate] = await Promise.all([
    realpath(resolve(root)).catch(() => resolve(root)),
    realpath(resolve(candidate)).catch(() => resolve(candidate)),
  ]);
  if (realRoot === realCandidate) {
    return true;
  }
  const rel = relative(realRoot, realCandidate);
  return rel.length > 0 && !rel.startsWith("..") && !isAbsolute(rel);
}

/**
 * The version, taken from a stream that may carry more than the version.
 *
 * A real run found this: promptfoo prints a multi-line update notice on stdout,
 * and taking the whole stream meant the banner was recorded as the producer
 * version of a piece of evidence. Only a bare version token counts, and the
 * LAST one wins, because the notice quotes older versions before the tool
 * prints its own.
 */
export function parseVersion(stdout: string): string | null {
  const versions = stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => /^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(line));
  return versions.at(-1) ?? null;
}

/**
 * Settings that apply to every invocation, including `--version`.
 *
 * Telemetry, sharing and the update check are all network calls, and the update
 * check also writes a notice to stdout.
 */
const PROMPTFOO_SAFETY_FLAGS: Readonly<Record<string, string>> = {
  PROMPTFOO_DISABLE_TELEMETRY: "1",
  PROMPTFOO_DISABLE_SHARING: "1",
  PROMPTFOO_DISABLE_UPDATE: "1",
  /**
   * Hide the process environment from templates. Without it, `{{ env.NAME }}`
   * anywhere in the config is replaced at LOAD time with the child's
   * environment (`renderEnvOnlyInObject`, `src/util/render.ts:31`, reading the
   * `env` global set in `src/util/templates.ts`) -- which includes forwarded
   * credentials. Against 591171a, `{{ env.PROMPTFOO_CONFIG_DIR }}` in a prompt
   * was replaced by a local path before the prompt was even parsed.
   */
  PROMPTFOO_DISABLE_TEMPLATE_ENV_VARS: "1",
};

/** Settings for the version probe. */
export function promptfooProbeEnvironment(): Record<string, string> {
  return { ...PROMPTFOO_SAFETY_FLAGS };
}

/**
 * Settings for an evaluation run, applied after the runtime layout.
 *
 * `PROMPTFOO_PASS_RATE_THRESHOLD=0` is what lets a completed evaluation with
 * failing or erroring cases exit normally. promptfoo 0.122.0 exits with
 * `PROMPTFOO_FAILED_TEST_EXIT_CODE` (default 100) when
 * `passRate < PROMPTFOO_PASS_RATE_THRESHOLD` (default 100), after writing the
 * output file (`src/node/doEval.ts:1007`, `1204-1218`). A pass rate is never
 * below zero, so with this setting that branch never fires; fatal errors still
 * exit non-zero through their own path (`DoEvalError`, lines 143-161). Evidence
 * being available says the evaluation COMPLETED, not that the candidate passed.
 *
 * Any other non-zero exit remains a failed run: nothing here, or in the shared
 * subprocess runner, treats a non-zero exit as success.
 */
export function promptfooEvaluationEnvironment(): Record<string, string> {
  return {
    ...PROMPTFOO_SAFETY_FLAGS,
    PROMPTFOO_PASS_RATE_THRESHOLD: "0",
  };
}

/** The complete environment an evaluation in `runDirectory` is given. */
export function promptfooEnvironment(
  runDirectory: string,
): Record<string, string> {
  return {
    ...runtimeLayout(runDirectory).environment,
    ...promptfooEvaluationEnvironment(),
  };
}

/**
 * The identity as it is recorded, built from the plan.
 *
 * One function, so the value the adapter writes onto the evidence and the value
 * `deriveExpectedEvaluation` predicts for the candidate cannot drift apart.
 */
export function verifiedIdentityOf(
  plan: EvaluationPlan,
  registration: Pick<ProviderRegistration, "reach" | "destination">,
): VerifiedEvaluationIdentity {
  return {
    provider_reach: registration.reach,
    destination_identity: registration.destination,
    workload_ref: plan.workloadRef,
    candidate_ref: plan.candidateRef,
    dataset_ref: plan.datasetRef,
    dataset_version: plan.datasetVersion,
    dataset_hash: plan.identities.dataset_hash,
    prompt_hash: plan.identities.prompt_hash,
    evaluator_hash: plan.identities.evaluator_hash,
    model_configuration_hash: plan.identities.model_configuration_hash,
    config_digest: plan.identities.config_digest,
    provider_id: plan.providerId,
  };
}

/**
 * The `measurements.expected_evaluation` a candidate must declare for evidence
 * from this spec to be admitted.
 *
 * Derived from the same normalised spec the run uses, so a caller writes the
 * expectation into the contract without hand-copying a hash. Never throws: an
 * unusable spec comes back as a rejection.
 */
export function deriveExpectedEvaluation(
  input: unknown,
  options: { readonly providers?: readonly ProviderRegistration[] } = {},
): { readonly expected_evaluation: ExpectedEvaluation } | SpecRejection {
  // The same preparation the run uses, so the expectation is for this spec
  // under this provider policy -- reach and destination included.
  const prepared = prepareEvaluation(input, options);
  if (isRejection(prepared)) {
    return prepared;
  }
  return {
    expected_evaluation: {
      provider_id: prepared.plan.providerId,
      configuration_hash: evaluationIdentityHash(
        verifiedIdentityOf(prepared.plan, prepared.registration),
      ),
    },
  };
}

/**
 * Step one of two: work out what would run, and what would leave.
 *
 * Returns the plan and the exact outbound projection WITHOUT executing
 * anything. This is the surface Milestone 3's interactive flow shows a person
 * before asking them to decide; a `remote` projection cannot be executed until
 * an authorization matching `projection.projection_digest` comes back.
 *
 * Never throws. An unusable spec, an unusable registry or an unregistered
 * provider all come back as reasons.
 */
export function prepareEvaluation(
  spec: unknown,
  options: {
    readonly providers?: readonly ProviderRegistration[];
  } = {},
):
  | {
      readonly plan: EvaluationPlan;
      readonly projection: EvaluationProjection;
      readonly registration: ProviderRegistration;
    }
  | SpecRejection {
  const planned = planEvaluation(spec);
  if (isRejection(planned)) {
    return planned;
  }

  const registryResult = buildProviderRegistry(options.providers ?? []);
  if ("reasons" in registryResult) {
    return { reasons: registryResult.reasons };
  }

  const registration = registryResult.registry.get(planned.plan.providerId);
  if (registration === undefined) {
    return {
      reasons: [
        `provider "${planned.plan.providerId}" is not registered, so nothing about it can be prepared`,
      ],
    };
  }

  const refusal = credentialPermissionProblem(planned.plan, registration);
  if (refusal !== null) {
    return { reasons: [refusal.message] };
  }

  return {
    plan: planned.plan,
    projection: describeOutboundProjection(planned.plan, registration),
    registration,
  };
}

/**
 * Why a remote run may not proceed, or `null` when it may.
 *
 * Missing, stale and mismatched are all the same answer to the caller -- the
 * evaluation does not run -- but they are different things to fix, so each says
 * which it is. A mismatch names the field that differs and never echoes the
 * authorization's own digest back as though it were authoritative.
 */
export function authorizationProblem(
  authorization: RemoteAuthorization | undefined,
  projection: EvaluationProjection,
  now: string,
  policy: AuthorizationTimePolicy,
): {
  readonly message: string;
  readonly detail: Record<string, unknown>;
} | null {
  if (authorization === undefined) {
    return {
      message: `provider "${projection.provider_id}" is remote, so the prompts and dataset rows would leave this machine; that requires a recorded authorization for this exact projection, and none was supplied`,
      detail: { reason: "missing" },
    };
  }

  // The record arrives with the request, so its shape is not trusted either.
  if (
    authorization === null ||
    typeof authorization !== "object" ||
    typeof authorization.provider_id !== "string" ||
    typeof authorization.projection_digest !== "string" ||
    typeof authorization.authorized_at !== "string"
  ) {
    return {
      message:
        "the authorization is not a well-formed record of provider, projection digest and time",
      detail: { reason: "malformed" },
    };
  }

  if (authorization.provider_id !== projection.provider_id) {
    return {
      message: `the authorization is for provider "${authorization.provider_id}", not "${projection.provider_id}"; an approval to send data to one destination is not an approval to send it to another`,
      detail: { reason: "provider_mismatch" },
    };
  }

  if (authorization.projection_digest !== projection.projection_digest) {
    return {
      message:
        "the authorization is for a different projection; the prompts, dataset rows, assertions, destination or credential names have changed since it was recorded, so what would be sent is not what was approved",
      detail: { reason: "projection_mismatch" },
    };
  }

  const authorizedAt = Date.parse(authorization.authorized_at);
  if (Number.isNaN(authorizedAt)) {
    return {
      message:
        "the authorization does not carry a readable timestamp, so its age cannot be established",
      detail: { reason: "unreadable_timestamp" },
    };
  }
  const currentTime = Date.parse(now);
  if (Number.isNaN(currentTime)) {
    return {
      message:
        "the current time could not be read, so the authorization's age cannot be established",
      detail: { reason: "unreadable_clock" },
    };
  }
  const ageMs = currentTime - authorizedAt;

  // Future first, and against its OWN allowance. The previous version reused
  // the max age as the future window, so with the one-hour default an
  // authorization dated thirty minutes AHEAD of the clock was accepted. A
  // record from the future is not a decision anyone has made yet.
  if (ageMs < -policy.clockSkewMs) {
    return {
      message:
        "the authorization is dated after the current time by more than the permitted clock skew, so it cannot be a decision that has already been made",
      detail: {
        reason: "future_dated",
        age_ms: ageMs,
        clock_skew_ms: policy.clockSkewMs,
      },
    };
  }
  if (ageMs > policy.maxAgeMs) {
    return {
      message:
        "the authorization is older than this adapter will accept; a decision to send a dataset somewhere is about that dataset now, not indefinitely",
      detail: { reason: "stale", age_ms: ageMs, max_age_ms: policy.maxAgeMs },
    };
  }

  return null;
}

/** How old, and how far ahead of the clock, an authorization may be. */
export interface AuthorizationTimePolicy {
  readonly maxAgeMs: number;
  /**
   * How far in the FUTURE an authorization may be dated and still count.
   * Default zero: nothing in the ANVILMARK documents justifies tolerating a
   * decision timestamped after the moment it is used.
   */
  readonly clockSkewMs: number;
}

export const DEFAULT_AUTHORIZATION_MAX_AGE_MS = 3_600_000;
export const DEFAULT_AUTHORIZATION_CLOCK_SKEW_MS = 0;

function isNonNegativeFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value) && value >= 0;
}

/**
 * Why a spec's credential names are not permitted by trusted policy, or null.
 *
 * Exact matching: the name forwarded to the process is the spelling policy
 * wrote. A syntactically valid name is not thereby a credential -- `PATH`,
 * `NODE_OPTIONS`, `HTTPS_PROXY` and `OPENAI_BASE_URL` are all valid names, and
 * none of them is refused by a pattern here. They are refused because trusted
 * policy did not list them (and, for the first three, cannot).
 */
export function credentialPermissionProblem(
  plan: EvaluationPlan,
  registration: ProviderRegistration,
): {
  readonly message: string;
  readonly detail: Record<string, unknown>;
} | null {
  const allowed = new Set(registration.credentialEnvNames);
  const refused = plan.credentialEnvNames.filter((name) => !allowed.has(name));
  if (refused.length === 0) {
    return null;
  }
  return {
    message: `the evaluation names credential variable(s) that provider policy for "${registration.id}" does not allow: ${refused.join(", ")}; a valid environment-variable name is not thereby a credential, and only trusted policy decides which variables a provider may read`,
    detail: {
      refused_names: refused,
      allowed_names: [...registration.credentialEnvNames].sort(
        compareCodeUnits,
      ),
      provider_id: registration.id,
    },
  };
}

/**
 * Check every per-case row against the provider and the summary counts.
 *
 * Returns `null` when the rows attribute to `providerId` and, classified with
 * `classifyCaseRow` (the rule promptfoo used to build the stats), tally exactly
 * to `stats`. Otherwise returns the first contradiction found. Pure, so the
 * rule can be checked against genuine promptfoo output directly.
 */
export function reconcileCaseOutcomes(
  rows: readonly {
    readonly provider?: unknown;
    readonly success?: unknown;
    readonly failureReason?: unknown;
  }[],
  stats: {
    readonly successes: number;
    readonly failures: number;
    readonly errors: number;
  },
  providerId: string,
): {
  readonly code: "malformed_output" | "ambiguous_attribution";
  readonly message: string;
  readonly detail: Record<string, unknown>;
} | null {
  const tally = { successes: 0, failures: 0, errors: 0 };
  for (const [index, row] of rows.entries()) {
    const rowProvider = providerIdOf(row.provider);
    if (rowProvider !== null && rowProvider !== providerId) {
      return {
        code: "ambiguous_attribution",
        message: `a per-case result names provider "${rowProvider}" while the run is attributed to "${providerId}"`,
        detail: { observed: rowProvider, declared: providerId },
      };
    }
    const classified = classifyCaseRow(row);
    if ("problem" in classified) {
      return {
        code: "malformed_output",
        message: `per-case result ${index} ${classified.problem}`,
        detail: { row_index: index },
      };
    }
    tally[classified.counted] += 1;
  }

  if (
    tally.successes !== stats.successes ||
    tally.failures !== stats.failures ||
    tally.errors !== stats.errors
  ) {
    return {
      code: "malformed_output",
      message: `the per-case results do not reconcile with the summary: the rows describe ${tally.successes} success(es), ${tally.failures} failure(s) and ${tally.errors} error(s), but the stats report ${stats.successes}, ${stats.failures} and ${stats.errors}`,
      detail: { rows: { ...tally }, stats: { ...stats } },
    };
  }
  return null;
}

/**
 * Is a stored evaluation still evidence about this configuration?
 *
 * Compares the combined configuration hash on the record with the hash of the
 * identity being asked about. Any change to dataset, prompt, candidate,
 * evaluator, or model configuration produces a different hash.
 */
export function isEvaluationCurrentFor(
  record: { readonly kind: string; readonly value: unknown },
  identity: EvaluationIdentity,
): boolean {
  if (record.kind !== "measured_evaluation") {
    return false;
  }
  const value = record.value as { configuration_hash?: unknown };
  return value.configuration_hash === evaluationIdentityHash(identity);
}

/**
 * Optional evaluation adapter.
 *
 * The adapter constructs the supported invocation itself rather than accepting
 * arbitrary arguments: `promptfoo eval -c <config> -o <artifact>` with
 * progress bar, table, and sharing disabled. It then parses the documented
 * OUTPUT FILE. Nothing is assumed about stdout, which promptfoo uses for
 * human-readable progress.
 */
export function createPromptfooAdapter(
  options: {
    readonly clock?: Clock;
    /**
     * The providers this adapter may execute, each declaring its reach.
     *
     * Empty by default, so nothing runs. An id that merely LOOKS like a model
     * name -- `browser`, `promptfoo:manual-input`, `mcp:server` -- is refused
     * because it was never registered, not because a pattern recognised it.
     */
    readonly providers?: readonly ProviderRegistration[];
    /**
     * How long a recorded authorization stays usable. Default one hour: a
     * decision about sending a dataset somewhere is about that dataset now, not
     * indefinitely. Must be a finite, non-negative number.
     */
    readonly authorizationMaxAgeMs?: number;
    /**
     * How far after the current time an authorization may be dated. Default
     * zero. Must be a finite, non-negative number.
     */
    readonly authorizationClockSkewMs?: number;
    /**
     * The program to run. Chosen HERE, once, and used for both the version
     * probe and the evaluation; a request cannot name another.
     */
    readonly executable?: string;
    /**
     * The environment a bare executable name resolves through and the child's
     * resolution variables come from. Captured at construction, so the probe
     * and the evaluation resolve the same name to the same program. Defaults
     * to a snapshot of the process environment.
     */
    readonly baseEnv?: Readonly<Record<string, string | undefined>>;
    /**
     * How credential values are looked up, by name. Called only for names the
     * spec declares AND trusted provider policy allows, and only after every
     * other check has passed. Defaults to the process environment.
     */
    readonly readEnv?: (name: string) => string | undefined;
    /**
     * Resource ceilings: `timeoutMs`, `maxOutputBytes`, `maxArtifactBytes`.
     * Trusted policy. A request may omit a limit or ask for a smaller one, never
     * a larger one. Each must be an integer within `RESOURCE_LIMIT_BOUNDS`.
     */
    readonly limits?: Partial<Record<keyof ResourceLimits, number>>;
    readonly versionArgs?: readonly string[];
    readonly probeTimeoutMs?: number;
    /**
     * Filesystem seam, injected when the adapter is CONSTRUCTED rather than
     * accepted per request. A caller must not be able to substitute the bytes
     * that get measured, hashed, and recorded as evidence.
     */
    readonly fs?: {
      readonly readFile?: (path: string) => Promise<string>;
      readonly stat?: (path: string) => Promise<{ size: number }>;
      readonly remove?: (path: string) => Promise<void>;
    };
  } = {},
): EvidenceAdapter<PromptfooRequest> {
  const clock = options.clock ?? systemClock;
  const baseEnv: Readonly<Record<string, string | undefined>> = Object.freeze({
    ...(options.baseEnv ?? process.env),
  });

  // Resolved ONCE, here, to a canonical absolute path, and hashed. The probe and
  // the evaluation both run exactly this file, and both first check that its
  // bytes still hash to this digest.
  const resolution = resolveExecutable(
    options.executable ?? "promptfoo",
    baseEnv,
  );
  const readEnv =
    options.readEnv ??
    ((name: string): string | undefined => process.env[name]);

  // --- trusted policy, validated once ---------------------------------------
  //
  // An unusable policy fails closed in BOTH probe and collect, before any
  // subprocess starts. A NaN max age made every age comparison false, which
  // accepted every authorization; policy that cannot be evaluated is not a
  // permissive default.
  const policyProblems: string[] = [];
  const registryResult = buildProviderRegistry(options.providers ?? []);
  if ("reasons" in registryResult) {
    policyProblems.push(...registryResult.reasons);
  }
  const maxAgeMs =
    options.authorizationMaxAgeMs ?? DEFAULT_AUTHORIZATION_MAX_AGE_MS;
  if (!isNonNegativeFiniteNumber(maxAgeMs)) {
    policyProblems.push(
      "authorizationMaxAgeMs must be a finite, non-negative number of milliseconds",
    );
  }
  const clockSkewMs =
    options.authorizationClockSkewMs ?? DEFAULT_AUTHORIZATION_CLOCK_SKEW_MS;
  if (!isNonNegativeFiniteNumber(clockSkewMs)) {
    policyProblems.push(
      "authorizationClockSkewMs must be a finite, non-negative number of milliseconds",
    );
  }
  const timePolicy: AuthorizationTimePolicy = { maxAgeMs, clockSkewMs };

  const ceilingsResult = resourceLimitCeilings(options.limits);
  if ("problems" in ceilingsResult) {
    policyProblems.push(...ceilingsResult.problems);
  }
  const probeTimeoutMs = options.probeTimeoutMs ?? PROBE_TIMEOUT_BOUNDS.default;
  if (!isBoundedInteger(probeTimeoutMs, PROBE_TIMEOUT_BOUNDS)) {
    policyProblems.push(
      `probeTimeoutMs must be an integer from ${PROBE_TIMEOUT_BOUNDS.min} to ${PROBE_TIMEOUT_BOUNDS.max}`,
    );
  }

  const policyRefusal = <T>(startedAt: string): AdapterOutcome<T> =>
    notAvailable(
      "failed",
      [
        adapterError(
          "invalid_adapter_policy",
          `this adapter was constructed with policy it cannot enforce, so it will not run anything: ${policyProblems.join("; ")}`,
          { reasons: [...policyProblems] },
        ),
      ],
      {
        adapter: PROMPTFOO_IDENTITY,
        started_at: startedAt,
        completed_at: clock(),
        provenance: {
          command_manifest: null,
          locator: null,
          raw_result_hash: null,
        },
        diagnostics: [],
      },
    );

  const versionArgs = options.versionArgs ?? ["--version"];
  const readFileAt =
    options.fs?.readFile ?? ((path: string) => readFile(path, "utf8"));
  const statAt = options.fs?.stat ?? ((path: string) => stat(path));
  const removeAt =
    options.fs?.remove ??
    ((path: string) => rm(path, { recursive: true, force: true }));

  const bareOutcomeMeta = (startedAt: string) => ({
    adapter: PROMPTFOO_IDENTITY,
    started_at: startedAt,
    completed_at: clock(),
    provenance: {
      command_manifest: null,
      locator: null,
      raw_result_hash: null,
    },
    diagnostics: [] as string[],
  });

  /** The launcher, if it resolved and still hashes to its construction digest. */
  const verifiedLauncher = async (
    startedAt: string,
    moment: string,
  ): Promise<
    | { readonly path: string; readonly digest: string }
    | { readonly refusal: AdapterOutcome<never> }
  > => {
    if ("problem" in resolution) {
      return {
        refusal: notAvailable(
          "unavailable",
          [adapterError("executable_not_found", resolution.problem)],
          bareOutcomeMeta(startedAt),
        ),
      };
    }
    const current = await digestFile(resolution.resolved.path);
    if (current !== resolution.resolved.digest) {
      return {
        refusal: notAvailable(
          "failed",
          [
            adapterError(
              "executable_changed",
              `the promptfoo launcher no longer matches the file this adapter resolved when it was constructed (checked ${moment}); a result from a program that changed cannot be attributed to the build that was probed`,
              { checked: moment, expected_digest: resolution.resolved.digest },
            ),
          ],
          bareOutcomeMeta(startedAt),
        ),
      };
    }
    return resolution.resolved;
  };

  const probe = async (probeOptions?: {
    readonly signal?: AbortSignal;
  }): Promise<AdapterOutcome<AdapterProbe>> => {
    const startedAt = clock();
    if (policyProblems.length > 0) {
      return policyRefusal<AdapterProbe>(startedAt);
    }
    const launcher = await verifiedLauncher(
      startedAt,
      "before the version probe",
    );
    if ("refusal" in launcher) {
      return launcher.refusal;
    }

    // The probe gets its own disposable directory, with the same redirection
    // the evaluation gets, rather than running in whatever directory the host
    // process happens to be in.
    const probeDirectory = await mkdtemp(join(tmpdir(), "anvilmark-probe-"));
    let outcome: Awaited<ReturnType<typeof runSubprocess>>;
    try {
      const runtime = await createRuntimeLayout(probeDirectory);
      outcome = await runSubprocess(
        {
          // The construction-time file, always. Any `executable` a caller
          // passes here is not read.
          executable: launcher.path,
          manifestExecutable: "promptfoo",
          workingDirectory: probeDirectory,
          manifestWorkingDirectory: "<probe-directory>",
          baseEnv,
          args: [...versionArgs],
          timeoutMs: probeTimeoutMs,
          maxOutputBytes: 8 * 1024,
          // Telemetry and the update check are network calls, and the update
          // check also PRINTS: without it disabled the banner lands on stdout
          // and becomes the "version".
          env: { ...runtime, ...promptfooProbeEnvironment() },
          ...(probeOptions?.signal === undefined
            ? {}
            : { signal: probeOptions.signal }),
        },
        { identity: PROMPTFOO_IDENTITY, clock },
      );
    } finally {
      await rm(probeDirectory, { recursive: true, force: true }).catch(
        () => undefined,
      );
    }

    if (!isAvailable(outcome)) {
      return outcome as AdapterOutcome<AdapterProbe>;
    }
    const version = parseVersion(outcome.value.stdout);
    if (version === null) {
      return notAvailable(
        "unsupported",
        [
          adapterError(
            "version_unavailable",
            "the tool did not report a version; an evaluation from an unidentified build cannot be attributed",
          ),
        ],
        {
          adapter: PROMPTFOO_IDENTITY,
          started_at: startedAt,
          completed_at: clock(),
          provenance: {
            command_manifest: outcome.value.manifest,
            locator: null,
            raw_result_hash: null,
          },
          diagnostics: outcome.diagnostics,
        },
      );
    }
    if (!isVerifiedPromptfooVersion(version)) {
      return notAvailable(
        "unsupported",
        [
          adapterError(
            "version_unsupported",
            `promptfoo ${version} is not a version whose output this adapter has verified (${VERIFIED_PROMPTFOO_VERSIONS.join(", ")}); its artifact parser, per-case semantics and exit handling are checked for those versions only`,
            {
              reported_version: version,
              verified_versions: [...VERIFIED_PROMPTFOO_VERSIONS],
            },
          ),
        ],
        {
          adapter: { ...PROMPTFOO_IDENTITY, version },
          started_at: startedAt,
          completed_at: clock(),
          provenance: {
            command_manifest: outcome.value.manifest,
            locator: null,
            raw_result_hash: null,
          },
          diagnostics: outcome.diagnostics,
        },
      );
    }
    return available(
      { version, capabilities: ["evaluation"] },
      {
        adapter: { ...PROMPTFOO_IDENTITY, version },
        started_at: startedAt,
        completed_at: clock(),
        provenance: {
          command_manifest: outcome.value.manifest,
          locator: null,
          raw_result_hash: outcome.value.raw_result_hash,
        },
        diagnostics: outcome.diagnostics,
      },
    );
  };

  return {
    identity: PROMPTFOO_IDENTITY,
    probe,

    async collect(request, collectOptions) {
      const startedAt = clock();

      // Policy is the adapter's own state; if it cannot be enforced nothing
      // below is meaningful.
      if (policyProblems.length > 0) {
        return policyRefusal<BuiltEvidence>(startedAt);
      }

      const bareMeta = (diagnostics: readonly string[] = []) => ({
        adapter: PROMPTFOO_IDENTITY,
        started_at: startedAt,
        completed_at: clock(),
        provenance: {
          command_manifest: null,
          locator: null,
          raw_result_hash: null,
        },
        diagnostics,
      });

      // --- caller inputs, before anything is executed ---------------------

      // A closed request. The fields that used to choose the program and its
      // environment are named explicitly in the refusal, because an honest
      // caller still passing them needs to know they now belong to adapter
      // construction -- and a hostile one must not have them silently dropped
      // while believing they took effect.
      const unexpected = (() => {
        try {
          return Object.keys(request as object).filter(
            (key) => !PROMPTFOO_REQUEST_FIELDS.includes(key),
          );
        } catch {
          return ["<unreadable request>"];
        }
      })();
      if (unexpected.length > 0) {
        return notAvailable(
          "failed",
          [
            adapterError(
              "unsupported_argument",
              `the request carries field(s) this adapter does not accept: ${unexpected.join(", ")}; the executable, its environment and credential lookup are chosen when the adapter is constructed, never per request`,
              { unexpected_fields: unexpected.sort(compareCodeUnits) },
            ),
          ],
          bareMeta(),
        );
      }

      // Resource limits are policy. The request may only narrow them, and a
      // value that is not a positive integer within the ceiling is refused
      // before anything is spawned -- a NaN timeout used to start promptfoo and
      // time it out at once.
      const ceilings =
        "ceilings" in ceilingsResult ? ceilingsResult.ceilings : null;
      if (ceilings === null) {
        return policyRefusal<BuiltEvidence>(startedAt);
      }
      const limitsResult = effectiveResourceLimits(
        {
          timeoutMs: request.timeoutMs,
          maxOutputBytes: request.maxOutputBytes,
          maxArtifactBytes: request.maxArtifactBytes,
        },
        ceilings,
      );
      if ("problems" in limitsResult) {
        return notAvailable(
          "failed",
          [
            adapterError(
              "invalid_resource_limit",
              `the request asks for resource limits this adapter will not apply: ${limitsResult.problems.join("; ")}`,
              {
                reasons: [...limitsResult.problems],
                ceilings: { ...ceilings },
              },
            ),
          ],
          bareMeta(),
        );
      }
      const limits = limitsResult.limits;
      const maxArtifactBytes = limits.maxArtifactBytes;

      const artifactName = request.outputFileName ?? "eval.json";
      if (!isSafeArtifactName(artifactName)) {
        return notAvailable(
          "failed",
          [
            adapterError(
              "unsafe_output_path",
              `"${artifactName}" is not a plain file name; the artifact name may not contain a path separator, a traversal segment, or an absolute path`,
              { output_file_name: artifactName },
            ),
          ],
          bareMeta(),
        );
      }

      // An arbitrary promptfoo config cannot be parsed soundly: the bytes that
      // decide pass or fail can hide in an assertion value, a variable, a
      // scenario or a provider id, and four review passes found a new hiding
      // place each time. Pointing at one is refused outright.
      //
      // This is checked BEFORE the version probe. Probing spawns a subprocess,
      // and there is nothing to learn from a tool that is about to be told no.
      if (request.configPath !== undefined) {
        return notAvailable(
          "unknown",
          [
            adapterError(
              "unsupported_configuration",
              "an existing promptfoo config cannot be used as the source of T3 evidence in this milestone; supply an evaluation spec instead, from which ANVILMARK generates the config",
              { config_path_supplied: true },
            ),
          ],
          bareMeta(),
        );
      }

      // The plan is computed ONCE, before anything is spawned. It owns a
      // canonical, frozen copy of the spec, the exact config bytes, and every
      // derived identity.
      const planned = planEvaluation(request.spec);
      if (isRejection(planned)) {
        return notAvailable(
          "unknown",
          [
            adapterError(
              "unsupported_configuration",
              `the evaluation spec is outside the supported subset, so what would run cannot be identified: ${planned.reasons.join("; ")}`,
              { reasons: planned.reasons },
            ),
          ],
          bareMeta(),
        );
      }
      const plan: EvaluationPlan = planned.plan;

      // --- who may run, and whether anything may leave -----------------------
      //
      // Both checks are BEFORE the probe. Nothing is spawned, and no prompt,
      // dataset row or credential is written anywhere, until they pass.

      // Policy was validated before the request was read, so this narrowing
      // cannot fail; it is kept so the type follows the check.
      if ("reasons" in registryResult) {
        return policyRefusal<BuiltEvidence>(startedAt);
      }
      const registry: ProviderRegistry = registryResult.registry;

      const registration = registry.get(plan.providerId);
      if (registration === undefined) {
        return notAvailable(
          "unknown",
          [
            adapterError(
              "provider_not_registered",
              `provider "${plan.providerId}" is not registered with this adapter, so it will not be executed; registration is explicit because a well-formed id can name an interactive, agentic or network capability that this milestone does not cover`,
              {
                provider_id: plan.providerId,
                registered: [...registry.keys()].sort(compareCodeUnits),
              },
            ),
          ],
          bareMeta(),
        );
      }

      // Trusted policy decides which variables this provider may read. This
      // runs before the probe and before any value is looked up, so a refused
      // name is never read at all.
      const credentialRefusal = credentialPermissionProblem(plan, registration);
      if (credentialRefusal !== null) {
        return notAvailable(
          "unknown",
          [
            adapterError(
              "credential_not_permitted",
              credentialRefusal.message,
              credentialRefusal.detail,
            ),
          ],
          bareMeta(),
        );
      }

      const projection = describeOutboundProjection(plan, registration);

      if (registration.reach === "remote") {
        const denial = authorizationProblem(
          request.authorization,
          projection,
          clock(),
          timePolicy,
        );
        if (denial !== null) {
          return notAvailable(
            "unknown",
            [
              adapterError("authorization_required", denial.message, {
                ...denial.detail,
                provider_id: projection.provider_id,
                destination: projection.destination,
                destination_identity: projection.destination_identity,
                projection_digest: projection.projection_digest,
                data_categories: [...projection.data_categories],
                credential_env_names: [...projection.credential_env_names],
              }),
            ],
            bareMeta(),
          );
        }
      }

      // The data directory itself must not be a symlink. A recursive cleanup
      // runs inside it, and a link means that happens somewhere the caller did
      // not name. Symlinked ANCESTORS are the platform's business — on macOS
      // /var is one — so only the final segment is checked.
      const declaredDirectory = resolve(request.dataDirectory);
      try {
        if ((await lstat(declaredDirectory)).isSymbolicLink()) {
          return notAvailable(
            "failed",
            [
              adapterError(
                "unsafe_output_path",
                "the data directory is a symbolic link; the artifact and its cleanup must stay inside the directory the caller named",
                { declared: request.dataDirectory },
              ),
            ],
            bareMeta(),
          );
        }
      } catch {
        return notAvailable(
          "failed",
          [
            adapterError(
              "unsafe_output_path",
              `the data directory "${request.dataDirectory}" could not be inspected`,
            ),
          ],
          bareMeta(),
        );
      }
      const realDataDirectory = await realpath(declaredDirectory).catch(
        () => declaredDirectory,
      );

      // --- version, from the executable that will actually run -------------

      const probed = await probe(
        collectOptions?.signal === undefined
          ? {}
          : { signal: collectOptions.signal },
      );
      if (!isAvailable(probed)) {
        return probed as AdapterOutcome<BuiltEvidence>;
      }
      const version = probed.value.version;
      const identity: AdapterIdentity = { ...PROMPTFOO_IDENTITY, version };

      // Credentials come from the plan, which is the same list that was hashed
      // into `model_configuration_hash`. There is no second list, so the set
      // that was hashed and the set the process receives cannot differ.
      const credentials: Record<string, string> = {};
      const missing: string[] = [];
      for (const name of plan.credentialEnvNames) {
        const value = readEnv(name);
        if (value === undefined || value.length === 0) {
          missing.push(name);
          continue;
        }
        credentials[name] = value;
      }
      if (missing.length > 0) {
        return notAvailable(
          "unavailable",
          [
            adapterError(
              "adapter_internal_error",
              `credential reference(s) not set in the environment: ${missing.join(", ")}`,
              { missing_credential_names: missing },
            ),
          ],
          { ...bareMeta(), adapter: identity },
        );
      }

      // --- unique run directory, removed in `finally` ----------------------

      const runDirectory = await mkdtemp(join(realDataDirectory, "run-"));
      let cleanupFailure: ReturnType<typeof adapterError> | null = null;

      const outcome = await (async (): Promise<
        AdapterOutcome<BuiltEvidence>
      > => {
        try {
          if (!(await isContainedIn(realDataDirectory, runDirectory))) {
            return notAvailable(
              "failed",
              [
                adapterError(
                  "unsafe_output_path",
                  "the run directory resolved outside the data directory",
                ),
              ],
              { ...bareMeta(), adapter: identity },
            );
          }

          // The generated config is the only input, and it is written inside
          // the run directory. Nothing from the caller's tree is read, so there
          // is no window in which an input could change under the run.
          const runtime = await createRuntimeLayout(runDirectory);
          const snapshotRoot = join(runDirectory, "snapshot");
          await mkdir(snapshotRoot, { recursive: true });
          const snapshotConfigPath = join(snapshotRoot, "promptfooconfig.json");
          // The bytes captured in the plan, not a re-render. Rendering again
          // here would be a second chance to produce something different.
          await writeFile(snapshotConfigPath, plan.configBytes, "utf8");

          const outputPath = join(runDirectory, artifactName);

          const beforeRun = await verifiedLauncher(
            startedAt,
            "before the evaluation",
          );
          if ("refusal" in beforeRun) {
            return beforeRun.refusal;
          }

          const run = await runSubprocess(
            {
              // The same pinned file the probe just ran.
              executable: beforeRun.path,
              manifestExecutable: "promptfoo",
              // promptfoo runs INSIDE the run directory, so a relative lookup
              // -- a Nunjucks loader, a relative path -- cannot reach the
              // repository or the host process's working directory.
              workingDirectory: runDirectory,
              manifestWorkingDirectory: "<run-directory>",
              // The supported invocation, built here. There is no pass-through
              // for caller arguments: a second `-o`, a different `-c`, or
              // `--share` would silently change what ran or where it went.
              // Paths are relative to the run directory, so the manifest names
              // no machine path.
              args: [
                "eval",
                "-c",
                join("snapshot", "promptfooconfig.json"),
                "-o",
                artifactName,
                "--no-progress-bar",
                "--no-table",
                "--no-share",
                "--no-write",
              ],
              env: {
                ...credentials,
                // Adapter-owned runtime layout and safety settings are applied
                // LAST so a credential cannot override them.
                ...runtime,
                ...promptfooEvaluationEnvironment(),
              },
              timeoutMs: limits.timeoutMs,
              maxOutputBytes: limits.maxOutputBytes,
              // The same construction-time environment the probe resolved
              // through, so one name cannot mean two programs.
              baseEnv,
              ...(collectOptions?.signal === undefined
                ? {}
                : { signal: collectOptions.signal }),
            },
            { identity, clock },
          );

          // Checked whether or not the run succeeded: a program that rewrote
          // itself while running produced no attributable result either way.
          const afterRun = await verifiedLauncher(
            startedAt,
            "after the evaluation",
          );
          if ("refusal" in afterRun) {
            return afterRun.refusal;
          }

          if (!isAvailable(run)) {
            return run as AdapterOutcome<BuiltEvidence>;
          }

          const runMeta = (rawHash: string | null) => ({
            adapter: identity,
            started_at: startedAt,
            completed_at: clock(),
            provenance: {
              command_manifest: run.value.manifest,
              locator: null,
              raw_result_hash: rawHash,
            },
            diagnostics: run.diagnostics,
          });

          // Size is checked before the bytes are read into memory.
          let artifactBytes = 0;
          try {
            artifactBytes = (await statAt(outputPath)).size;
          } catch {
            return notAvailable(
              "failed",
              [
                adapterError(
                  "malformed_output",
                  "the tool exited successfully but wrote no result artifact where one was requested",
                  { output_file_name: artifactName },
                ),
              ],
              runMeta(null),
            );
          }
          if (artifactBytes > maxArtifactBytes) {
            return notAvailable(
              "failed",
              [
                adapterError(
                  "artifact_too_large",
                  `the result artifact is ${artifactBytes} bytes, beyond the ${maxArtifactBytes} this adapter will read`,
                  { artifact_bytes: artifactBytes, limit: maxArtifactBytes },
                ),
              ],
              runMeta(null),
            );
          }

          const artifact = await readFileAt(outputPath);
          const artifactHash = createHash("sha256")
            .update(artifact, "utf8")
            .digest("hex");

          let parsedJson: unknown;
          try {
            parsedJson = JSON.parse(artifact) as unknown;
          } catch {
            return notAvailable(
              "failed",
              [
                adapterError(
                  "malformed_output",
                  "the result artifact is not valid JSON and cannot be trusted as evidence",
                ),
              ],
              runMeta(artifactHash),
            );
          }

          const parsed = PromptfooOutputSchema.safeParse(parsedJson);
          if (!parsed.success) {
            return notAvailable(
              "failed",
              [
                adapterError(
                  "malformed_output",
                  "the result artifact does not match the documented promptfoo output envelope",
                  { issues: parsed.error.issues.length },
                ),
              ],
              runMeta(artifactHash),
            );
          }

          const output = parsed.data;
          const prompts = output.results.prompts ?? [];

          // When the artifact says which promptfoo wrote it, that must be the
          // build that was probed and pinned. An artifact claiming another
          // version is not the output of the program this adapter ran.
          const artifactVersion = artifactPromptfooVersion(parsedJson);
          if (artifactVersion !== undefined && artifactVersion !== version) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "identity_mismatch",
                  `the artifact reports promptfoo ${String(artifactVersion)} but the probed binary is ${version}`,
                  {
                    artifact_version: artifactVersion,
                    probed_version: version,
                  },
                ),
              ],
              runMeta(artifactHash),
            );
          }

          // --- attribution ---------------------------------------------------

          const { providers, sources } = collectProviders(output);

          if (providers.length === 0) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "ambiguous_attribution",
                  "the artifact names no provider anywhere, so the result cannot be attributed to a candidate",
                  { searched: sources },
                ),
              ],
              runMeta(artifactHash),
            );
          }

          if (providers.length > 1) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "ambiguous_attribution",
                  `the run covered ${providers.length} providers (${providers.join(", ")}); an aggregate over several providers is not a measurement of one candidate`,
                  { providers, sources },
                ),
              ],
              runMeta(artifactHash),
            );
          }

          const observedProvider = providers[0] ?? null;
          if (observedProvider === null) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "ambiguous_attribution",
                  "no provider identity could be established from the artifact",
                  { searched: sources },
                ),
              ],
              runMeta(artifactHash),
            );
          }

          // The spec declares the provider; the artifact reports what ran. A
          // difference is an attribution failure, not a detail to record.
          if (observedProvider !== plan.providerId) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "ambiguous_attribution",
                  `the run used provider "${observedProvider}" but the spec declares "${plan.providerId}"`,
                  { observed: observedProvider, declared: plan.providerId },
                ),
              ],
              runMeta(artifactHash),
            );
          }

          // The generated config is what ran. Re-reading it confirms the tool
          // did not rewrite its own input; nothing in the caller's tree was
          // read at any point, so there is no external window to close.
          const executedDigest = digestOf(await readFileAt(snapshotConfigPath));
          if (executedDigest !== plan.identities.config_digest) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "malformed_identity",
                  "the configuration changed while the evaluation was running, so the result cannot be attributed to either version",
                ),
              ],
              runMeta(artifactHash),
            );
          }

          const stats = output.results.stats;
          const errors = stats.errors ?? 0;
          const attempted = stats.successes + stats.failures + errors;

          // --- the artifact must describe THIS evaluation ---------------------
          //
          // With exactly one provider, promptfoo runs every prompt against
          // every row, so the case count is fixed by the spec before the tool
          // starts. An artifact reporting a different number is describing a
          // different run, and a fixture reporting 38 successes for a
          // one-row, one-prompt spec was being recorded as available T3
          // evidence.
          const expectedCases = expectedCaseCount(plan);
          if (expectedCases === 0) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "malformed_identity",
                  "the plan describes no cases at all, so there is nothing an artifact could be evidence of",
                ),
              ],
              runMeta(artifactHash),
            );
          }
          if (attempted !== expectedCases) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "malformed_output",
                  `the run reported ${attempted} case(s) but this evaluation has ${expectedCases} (${plan.spec.dataset.rows.length} row(s) times ${plan.spec.prompts.length} prompt(s)); the artifact does not describe the evaluation that was requested`,
                  {
                    reported_cases: attempted,
                    expected_cases: expectedCases,
                    rows: plan.spec.dataset.rows.length,
                    prompts: plan.spec.prompts.length,
                  },
                ),
              ],
              runMeta(artifactHash),
            );
          }

          // --- every case must agree with the summary ------------------------
          //
          // Counting cases is not enough: an artifact whose stats report one
          // success while its only row reports `success: false` has the right
          // TOTAL and the wrong result. So the per-case rows are required, and
          // each is classified exactly as promptfoo classified it when it
          // produced the stats. See `classifyCaseRow` for the pinned source.
          const caseRows = output.results.results;
          if (caseRows === undefined) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "malformed_output",
                  "the artifact carries no per-case results, so its summary counts cannot be checked against the cases they claim to summarise",
                ),
              ],
              runMeta(artifactHash),
            );
          }
          if (caseRows.length !== expectedCases) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  "malformed_output",
                  `the artifact carries ${caseRows.length} per-case result(s) but reports ${expectedCases} case(s); the two halves of the same artifact disagree`,
                  {
                    per_case_rows: caseRows.length,
                    expected_cases: expectedCases,
                  },
                ),
              ],
              runMeta(artifactHash),
            );
          }

          // Each row must name exactly one planned prompt-by-row pair and
          // restate that pair's prompt, variables, assertions and description.
          const binding = bindResultRows(plan, {
            prompts: output.results.prompts,
            results: caseRows,
          });
          if (binding !== null) {
            return notAvailable(
              "unknown",
              [adapterError(binding.code, binding.message, binding.detail)],
              runMeta(artifactHash),
            );
          }

          const reconciliation = reconcileCaseOutcomes(
            caseRows,
            { successes: stats.successes, failures: stats.failures, errors },
            plan.providerId,
          );
          if (reconciliation !== null) {
            return notAvailable(
              "unknown",
              [
                adapterError(
                  reconciliation.code,
                  reconciliation.message,
                  reconciliation.detail,
                ),
              ],
              runMeta(artifactHash),
            );
          }

          const metrics: Record<string, number> = {
            successes: stats.successes,
            failures: stats.failures,
            errors,
            cases_attempted: attempted,
          };
          if (attempted > 0) {
            metrics.pass_rate = stats.successes / attempted;
          }
          const single = prompts.length === 1 ? prompts[0]?.metrics : undefined;
          for (const [name, value] of Object.entries(
            single?.namedScores ?? stats.namedScores ?? {},
          )) {
            metrics[name] = value;
          }
          if (single !== undefined) {
            if (typeof single.totalLatencyMs === "number") {
              metrics.total_latency_ms = single.totalLatencyMs;
            }
            if (typeof single.cost === "number") {
              metrics.cost = single.cost;
            }
            if (typeof single.score === "number") {
              metrics.prompt_score = single.score;
            }
          }
          const usage = stats.tokenUsage;
          if (usage !== undefined) {
            for (const [key, name] of [
              ["total", "token_usage_total"],
              ["prompt", "token_usage_prompt"],
              ["completion", "token_usage_completion"],
              ["cached", "token_usage_cached"],
              ["numRequests", "token_usage_requests"],
            ] as const) {
              const value = (usage as Record<string, unknown>)[key];
              if (typeof value === "number") {
                metrics[name] = value;
              }
            }
          }

          const observedAt =
            output.results.timestamp ?? output.timestamp ?? startedAt;
          const envelopeVersion =
            output.results.version ?? output.version ?? null;

          // Every recorded field comes from the plan, which came from the
          // validated spec. Nothing here is a caller declaration that was
          // copied through without being checked.
          const verified = verifiedIdentityOf(plan, registration);

          const built = buildEvidenceRecord({
            id: request.evidenceId,
            kind: "measured_evaluation",
            subject: `${plan.candidateRef}.quality`,
            claim: `measured evaluation of ${plan.candidateRef} on ${plan.datasetRef}@${plan.datasetVersion}`,
            producer: { name: "promptfoo", version },
            observed_at: observedAt,
            source: {
              type: "local_command",
              locator: "redacted-command-manifest",
            },
            command_manifest: run.value.manifest,
            applies_to: {
              candidate_ref: plan.candidateRef,
              workload_ref: plan.workloadRef,
              hardware_ref: null,
              constraint_refs: [...request.constraintRefs],
            },
            value: {
              dataset_ref: plan.datasetRef,
              dataset_version: plan.datasetVersion,
              candidate_ref: plan.candidateRef,
              configuration_hash: evaluationIdentityHash(verified),
              identity: {
                workload_ref: plan.workloadRef,
                dataset_hash: plan.identities.dataset_hash,
                prompt_hash: plan.identities.prompt_hash,
                evaluator_hash: plan.identities.evaluator_hash,
                model_configuration_hash:
                  plan.identities.model_configuration_hash,
                config_digest: plan.identities.config_digest,
                provider_id: observedProvider,
              },
              metrics,
              result_artifact_hash: artifactHash,
            },
            units: { ...(request.metricUnits ?? {}) },
            assumptions: [
              `evaluated against dataset ${plan.datasetRef} version ${plan.datasetVersion}`,
              ...(envelopeVersion === null
                ? []
                : [`promptfoo result envelope version ${envelopeVersion}`]),
            ],
            exclusions: [
              "results do not transfer to a different prompt, evaluator, dataset, provider, or model configuration",
            ],
            raw_result_hash: artifactHash,
            confidence: "high",
            caveats: [
              // Persisted in the record, where the contract's identity block
              // has no field for them yet (see amendment 5 in
              // docs/vnext/07-schema-amendment-proposal.md). They are also
              // bound into `configuration_hash`.
              `run through provider "${registration.id}" with ${registration.reach} reach at destination "${registration.destination}"; the result does not apply to another reach or destination, and the destination is declared by provider policy rather than observed`,
              `promptfoo launcher ${afterRun.digest} was verified unchanged before the version probe, before the run and after it; this pins the launcher file only, not promptfoo's transitive package dependencies`,
              ...(stats.failures > 0
                ? [`${stats.failures} case(s) failed during the run`]
                : []),
              ...(errors > 0
                ? [`${errors} case(s) errored during the run`]
                : []),
            ],
            refresh: { policy: "never", expires_at: null },
            standing: "available",
          });

          if (!built.ok) {
            return notAvailable("failed", built.errors, runMeta(artifactHash));
          }
          return available(built.value, runMeta(artifactHash));
        } finally {
          // The run directory is created by this adapter and removed by it on
          // every path. Nothing the caller owns is ever removed.
          //
          // A failure here is NOT swallowed: an artifact left on disk is a
          // result that outlives the run, and the caller has to know.
          try {
            await removeAt(runDirectory);
            cleanupFailure = null;
          } catch (error) {
            cleanupFailure = adapterError(
              "cleanup_failed",
              // No path and no artifact content: safe to log verbatim.
              `the run directory could not be removed after the evaluation${
                error instanceof Error && error.name.length > 0
                  ? ` (${error.name})`
                  : ""
              }`,
            );
          }
        }
      })();

      // Evidence whose working directory may still exist is not evidence the
      // adapter can vouch for, so an unconfirmed cleanup withdraws it.
      if (cleanupFailure !== null) {
        return notAvailable("failed", [cleanupFailure], {
          adapter: outcome.adapter,
          started_at: outcome.started_at,
          completed_at: clock(),
          provenance: outcome.provenance,
          diagnostics: outcome.diagnostics,
        });
      }
      return outcome;
    },
  };
}
