import { z } from "zod/v4";

import {
  IdSchema,
  NonEmptyStringSchema,
  RefSchema,
  TimestampSchema,
} from "./primitives.js";

/**
 * Decision scope, ratified in doc 06 section 1 as a discriminated union over
 * `workload | component | project`.
 *
 * An explicit `kind` tag is used rather than inferring the variant from which
 * `*_ref` happens to be present: an untagged shape is ambiguous when both or
 * neither ref appears, and the ratified wording is explicitly a discriminated
 * union. `component_ref` names an architecture node, which is how this
 * contract represents a component.
 */
export const DecisionScopeSchema = z.discriminatedUnion("kind", [
  z.strictObject({
    kind: z.literal("workload"),
    workload_ref: RefSchema,
  }),
  z.strictObject({
    kind: z.literal("component"),
    component_ref: RefSchema,
  }),
  z.strictObject({ kind: z.literal("project") }),
]);

export type DecisionScope = z.infer<typeof DecisionScopeSchema>;

export const DecisionStatusSchema = z.enum([
  "draft",
  "proposed",
  "approved",
  "superseded",
  "rejected",
]);

export type DecisionStatus = z.infer<typeof DecisionStatusSchema>;

/**
 * Rationale may be generated by the user's intelligence, but the contract
 * records that fact. `reviewed_by_user` is a precondition of approval and can
 * never be set by an agent on the user's behalf.
 */
export const RationaleSchema = z.strictObject({
  summary: NonEmptyStringSchema,
  generated_by: NonEmptyStringSchema.nullable().default(null),
  reviewed_by_user: z.boolean().default(false),
});

export type Rationale = z.infer<typeof RationaleSchema>;

export const DecisionSchema = z.strictObject({
  id: IdSchema,
  /** Incremented whenever resolved approved content changes. */
  revision: z.int().min(1),
  status: DecisionStatusSchema,
  scope: DecisionScopeSchema,
  selected_candidate_ref: RefSchema.nullable().default(null),
  alternatives: z.array(RefSchema).default([]),
  satisfies_constraints: z.array(RefSchema).default([]),
  unresolved_constraints: z.array(RefSchema).default([]),
  evidence_refs: z.array(RefSchema).default([]),
  rationale: RationaleSchema,
  created_at: TimestampSchema,
  updated_at: TimestampSchema.nullable().default(null),
});

export type Decision = z.infer<typeof DecisionSchema>;
