import type { Metadata } from "next";
import Link from "next/link";

import { HardwareSizingCockpit } from "../components/HardwareSizingCockpit";
import { SiteFooter } from "../components/site-footer";
import { SiteHeader } from "../components/site-header";
import { PlaygroundClient } from "./PlaygroundClient";
import { loadPlaygroundModel } from "./sample";

export const metadata: Metadata = {
  title: "Hardware sizing and contract checks · ANVILMARK playground",
  description:
    "Size a declared deployment, export its assumptions, and explore real Atlas code-to-contract checks.",
};

export default function PlaygroundPage() {
  const result = loadPlaygroundModel();

  return (
    <div className="min-h-screen bg-ink font-sans text-canvas selection:bg-gold selection:text-ink">
      <SiteHeader />

      <main className="pt-[var(--am-header-h)]">
        <div className="border-b border-line-muted bg-surface/80 bg-grain">
          <div className="mx-auto flex max-w-[108rem] flex-wrap items-end justify-between gap-4 px-5 py-8 sm:px-8">
            <div>
              <div className="mb-2.5 flex items-center gap-2 text-xs text-sand/60">
                <Link
                  href="/"
                  className="inline-flex items-center gap-1 transition-colors hover:text-gold"
                >
                  <span aria-hidden="true">←</span> Back to Home
                </Link>
                <span className="text-line-muted">/</span>
                <span className="text-sand/90">Playground</span>
              </div>
              <p className="text-[11px] font-medium uppercase tracking-brand text-gold">
                Sizing and contract workspace
              </p>
              <h1 className="mt-3 font-brand text-3xl font-light leading-tight text-canvas sm:text-4xl">
                Size the deployment. Check the implementation.
              </h1>
              <p className="mt-3 max-w-2xl text-sm leading-6 text-sand/80">
                Explore memory requirements and the evidence still needed for a
                deployment. Then change the Atlas model or redaction path and
                run the actual conformance checker.
              </p>
            </div>
            {result.ok ? (
              <span className="whitespace-nowrap border border-line-muted bg-ink px-3 py-1.5 font-mono text-[11px] text-sand/80">
                Atlas snapshot {result.model.generatedAsOf}
              </span>
            ) : null}
          </div>
        </div>

        <HardwareSizingCockpit />

        <div
          data-testid="synthetic-data-notice"
          role="note"
          className="sticky top-[var(--am-header-h)] z-20 border-b border-gold/30 bg-[#1e1708] px-5 py-2 text-center text-xs font-medium text-goldsoft sm:px-8"
        >
          Interactive synthetic Atlas example — runs actual @anvilmark/scanner
          &amp; @anvilmark/conformance engine in a bounded worker.
        </div>

        <div className="overflow-x-hidden">
          <PlaygroundClient />
        </div>

        {result.ok ? (
          <div className="mx-auto max-w-[108rem] px-5 pb-12 text-[11px] leading-5 text-steel sm:px-8">
            <p className="m-0">
              Provenance: generated by{" "}
              <span className="font-mono text-sand/70">
                {result.model.source.generator}
              </span>{" "}
              from base commit{" "}
              <span className="font-mono text-sand/70">
                {result.model.source.baseCommit.slice(0, 12)}
              </span>
              . A recorded pass was evaluated at its snapshot time and is not a
              claim about current files.
            </p>
          </div>
        ) : null}
      </main>

      <SiteFooter />
    </div>
  );
}
