import type { ProjectContract } from "@anvilmark/project-contract";

import type { Observation, ScanContent } from "./artifact.js";
import { compareStrings } from "./model.js";
import { SCAN_CONFIG_FORMAT } from "./version.js";

/**
 * A DRAFT scan declaration file from a scan made without declarations.
 *
 * Everything the scanner observed becomes a suggestion; nothing is asserted.
 * A value is filled in only when the contract leaves exactly one choice (one
 * remote provider node, one candidate for that provider and operation kind,
 * one local service node). Everything else is a commented line for the user
 * to complete. The result is valid YAML that `parseScanConfig` accepts as is.
 */

type Call = Extract<Observation, { kind: "provider_call" }>;

const HANDLER_EXPORTS = ["GET", "POST", "PUT", "PATCH", "DELETE"];

function yaml(value: string): string {
  return JSON.stringify(value);
}

function idPart(text: string): string {
  return (
    text
      .toLowerCase()
      .replace(/\.[cm]?[jt]sx?$/, "")
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "") || "root"
  );
}

function commonDirectory(paths: readonly string[]): string {
  const split = paths.map((path) => path.split("/").slice(0, -1));
  const first = split[0] ?? [];
  let length = 0;
  while (
    length < first.length &&
    split.every((parts) => parts[length] === first[length])
  )
    length += 1;
  return length === 0 ? "." : first.slice(0, length).join("/");
}

function modelFits(call: Call, componentKind: string): boolean {
  if (call.operation_kind === "embedding")
    return componentKind === "embedding_model";
  if (call.operation_kind === "inference")
    return componentKind !== "embedding_model";
  return false;
}

export function draftDeclarations(input: {
  readonly content: ScanContent;
  readonly contract: ProjectContract;
  readonly repositoryRoot: string;
}): string {
  const { content, contract } = input;
  const calls = content.observations
    .filter((o): o is Call => o.kind === "provider_call")
    .sort(
      (left, right) =>
        compareStrings(left.location.path, right.location.path) ||
        left.location.start.line - right.location.start.line,
    );
  const remoteNodes = contract.architecture.nodes.filter(
    (node) => node.trust_boundary === "remote_provider",
  );
  const localServices = contract.architecture.nodes.filter(
    (node) => node.trust_boundary === "local" && node.kind === "service",
  );
  const lines: string[] = [
    "# DRAFT scan declarations, generated by `anvilmark scan draft-config` from a",
    `# scan of ${input.repositoryRoot} (snapshot ${content.repository.snapshot_hash}).`,
    "# Every entry is a suggestion from observed code, not a fact. Review each one,",
    "# complete or delete the commented lines, then save as .anvilmark/scanner.yaml.",
    `format: ${SCAN_CONFIG_FORMAT}`,
    `repository_root: ${yaml(input.repositoryRoot)}`,
    "",
    "# Observed provider calls:",
  ];
  if (calls.length === 0)
    lines.push(
      "#   none. Unsupported SDKs and unresolved calls are listed by `anvilmark scan show --section unknowns`.",
    );
  for (const call of calls) {
    const endpoint =
      call.endpoint.provider ??
      (call.endpoint.selection === "runtime_selected"
        ? "chosen at run time"
        : call.endpoint.selection === "unlinked"
          ? "client not linked"
          : (call.endpoint.host ?? "unknown"));
    const model =
      call.model.kind === "literal" ? call.model.value : call.model.kind;
    lines.push(
      `#   ${call.location.path}:${call.location.start.line} ${call.recognizer} ${call.operation} [${call.operation_kind}] -> ${endpoint}, model ${model}`,
    );
  }
  const unsupported = content.unknowns
    .filter((unknown) => unknown.reason === "unsupported_provider_sdk")
    .map(
      (unknown) =>
        `#   ${unknown.location.path}:${unknown.location.start.line} ${unknown.detail.join(", ")}`,
    )
    .filter((line, index, all) => all.indexOf(line) === index);
  if (unsupported.length > 0)
    lines.push(
      "# Calls into AI SDKs without a recognizer (conformance cannot check these):",
      ...unsupported,
    );

  // Sources: request handlers in files that call a provider.
  const handlerFiles = [...new Set(calls.map((call) => call.location.path))];
  const handlers = handlerFiles.flatMap((path) =>
    calls
      .filter((call) => call.location.path === path)
      .map((call) => call.location.symbol)
      .filter(
        (symbol): symbol is string =>
          symbol !== null && HANDLER_EXPORTS.includes(symbol),
      )
      .filter((symbol, index, all) => all.indexOf(symbol) === index)
      .map((symbol) => ({ path, symbol })),
  );
  lines.push("", "sources: []");
  if (handlers.length > 0) {
    lines.push(
      "# Request handlers that call a provider. If a request carries data you",
      "# classify (for example user messages), declare its parameter as a source:",
    );
    for (const handler of handlers)
      lines.push(
        `#  - id: source.${idPart(handler.path)}_${handler.symbol.toLowerCase()}`,
        "#    data_classification: user_message   # a label your contract declares",
        `#    function: { path: ${yaml(handler.path)}, export: ${handler.symbol} }`,
        "#    from: parameter",
        "#    parameter: 0",
      );
  }
  lines.push(
    "",
    "sanitizers: []",
    "# Declare functions that redact a classification before it leaves, e.g.:",
    "#  - id: sanitizer.pii",
    '#    function: { path: "src/redact.ts", export: redactTicket }',
    "#    clears: [raw_customer_ticket]",
    "#    produces: redacted_customer_ticket",
  );

  // Sinks: one per recognizer, scoped to where its calls were observed.
  const recognizers = [...new Set(calls.map((call) => call.recognizer))].sort(
    compareStrings,
  );
  lines.push("", recognizers.length === 0 ? "sinks: []" : "sinks:");
  for (const recognizer of recognizers) {
    const ofRecognizer = calls.filter((call) => call.recognizer === recognizer);
    const providers = [
      ...new Set(ofRecognizer.map((call) => call.endpoint.provider)),
    ];
    const kinds = [...new Set(ofRecognizer.map((call) => call.operation_kind))];
    const matching =
      providers.length === 1 && providers[0] !== null
        ? contract.candidates.filter(
            (candidate) =>
              (candidate.deployment.mode === "local"
                ? candidate.deployment.runtime
                : candidate.deployment.provider) === providers[0] &&
              ofRecognizer.every((call) =>
                modelFits(call, candidate.component_kind),
              ),
          )
        : [];
    lines.push(
      `  - id: sink.${idPart(recognizer)}`,
      `    recognizer: ${yaml(recognizer)}`,
      `    paths: [${yaml(commonDirectory(ofRecognizer.map((call) => call.location.path)))}]`,
    );
    if (remoteNodes.length === 1 && remoteNodes[0] !== undefined)
      lines.push(
        `    architecture_node_ref: ${remoteNodes[0].id}   # the contract's only remote_provider node`,
      );
    else
      lines.push(
        "    # architecture_node_ref: the node these calls reach (e.g. a remote_provider node)",
      );
    if (matching.length === 1 && matching[0] !== undefined)
      lines.push(
        `    candidate_ref: ${matching[0].id}   # the only candidate for ${providers[0] ?? ""} ${kinds.join("/")} calls`,
      );
    else
      lines.push(
        `    # candidate_ref: the approved candidate for these calls (providers seen: ${providers.map((provider) => provider ?? "unresolved").join(", ")}; kinds: ${kinds.join(", ")})`,
      );
    if (ofRecognizer.some((call) => call.model.kind === "runtime_selected"))
      lines.push(
        "    # models: [...]   # declare the values a run-time model can take, if you know them",
      );
    if (
      ofRecognizer.some(
        (call) =>
          call.endpoint.selection === "runtime_selected" ||
          call.endpoint.selection === "unlinked",
      )
    )
      lines.push(
        "    # providers: [...]   # declare the providers a run-time endpoint can reach, if you know them",
      );
  }

  // Components: the files holding provider calls.
  const componentNode =
    localServices.length === 1 && localServices[0] !== undefined
      ? localServices[0].id
      : null;
  lines.push("");
  if (componentNode === null || handlerFiles.length === 0) {
    lines.push(
      "components: []",
      "# Declare which files implement which workload, e.g.:",
      ...handlerFiles.flatMap((path) => [
        `#  - id: component.${idPart(path)}`,
        `#    path: ${yaml(path)}`,
        "#    architecture_node_ref: <a service node>",
        "#    workload_ref: <a workload>",
      ]),
    );
  } else {
    lines.push("components:");
    for (const path of handlerFiles)
      lines.push(
        `  - id: component.${idPart(path)}`,
        `    path: ${yaml(path)}`,
        `    architecture_node_ref: ${componentNode}   # the contract's only local service node`,
        "    workload_ref: null   # set the workload this file implements",
      );
  }
  return `${lines.join("\n")}\n`;
}
